"""add station_rmcab_id and lat/lon fields

Revision ID: ab4c30080fce
Revises: 9b2db884ad8a
Create Date: 2025-10-04 15:09:05.790236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4c30080fce'
down_revision: Union[str, Sequence[str], None] = '9b2db884ad8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('station_rmcab_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stations_station_rmcab_id'), 'stations', ['station_rmcab_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_station_rmcab_id'), table_name='stations')
    op.drop_column('stations', 'station_rmcab_id')
    # ### end Alembic commands ###
