"""update subscription table with name fields and preference type

Revision ID: d27bcfbf4c31
Revises: 6bf7145dc559
Create Date: 2025-10-04 21:05:53.744191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27bcfbf4c31'
down_revision: Union[str, Sequence[str], None] = '6bf7145dc559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('station_preference_type', sa.String(length=20), nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('subscriptions', 'all_stations')
    op.drop_column('subscriptions', 'subscribed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscribed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('all_stations', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('subscriptions', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'station_preference_type')
    op.drop_column('subscriptions', 'last_name')
    op.drop_column('subscriptions', 'first_name')
    # ### end Alembic commands ###
